FROM node:18.18.0
RUN npm install -g gulp-cli bower grunt
# Add colors to the terminal:
RUN echo "PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '" >> /root/.bashrc